language: minimal

services:
    docker

jobs:
    include:
      - stage: backend-lint
        script: make backend.lint
      - stage: backend-proxy-lint
        script: make backend-proxy.lint
      - stage: backend-test
        script: make backend.test
        after_Script: make clean
