version: '3.8'

services:
  mysql-db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'classroom-db'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'group18'
       MYSQL_ROOT_PASSWORD: 'group18'

  backend-service:
    build: 
        context: './backend-service'
        dockerfile: 'app.Dockerfile'
    image: backend-service:tag
    environment:
      BOT_SERVER_SECRET_KEY: 'Sample'
      MYSQL_DATABASE: 'classroom-db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'group18'
      MYSQL_ROOT_PASSWORD: 'group18'
      MYSQL_HOST: 'localhost'
      MYSQL_CONNECTION_PORT: '3306'
    ports:
      - "8000:8000"
    depends_on:
      - "mysql-db"