version: '3.2'

services:

  ui:
    image: bot-ui:local
    restart: always
    ports:
      - 3000:80
    hostname: ui

  mysql-db:
    container_name: 'mysql'
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'classroom_db'
       MYSQL_USER: 'root'
       MYSQL_ROOT_PASSWORD: 'group18'
    restart: on-failure

  backend-service:
    build: 
        context: './backend-service'
        dockerfile: 'app.Dockerfile'
    container_name: backend-service
    image: backend-service:tag
    env_file: backend-service/sample.env
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mysql-db